---
# TODO: Migrate to the new role

- name: update httpd-le-ssl.conf
  template:
    src: httpd-le-ssl.j2.conf
    dest: /etc/httpd/conf/httpd-le-ssl.conf
  notify:
    - restart apache

- name: update conf.d
  template:
    src: "httpd_conf.d/{{ item }}"
    dest: "/etc/httpd/conf.d/{{ item|regex_replace('\\.j2\\.conf$', '.conf') }}"
  with_items:
    - "getfursu.it.j2.conf"
  notify:
    - restart apache
  tags: conf.d

- name: update conf.modules.d
  template:
    src: "httpd_conf.modules.d/{{ item }}"
    dest: "/etc/httpd/conf.modules.d/{{ item|regex_replace('\\.j2\\.conf$', '.conf') }}"
  with_items:
    - "00-brotli.j2.conf"
  notify:
    - restart apache

- name: update logrotate.d/httpd
  template:
    src: logrotate.d/httpd.j2
    dest: /etc/logrotate.d/httpd
    backup: yes

# TODO: Manage txkillswitch binary

- name: create systemd unit for txkillswitch
  template:
    mode: 0644
    src: txkillswitch.service.j2
    dest: /etc/systemd/system/txkillswitch.service
  notify:
    - reload systemd
    - restart txkillswitch
  tags: txkillswitch

- name: enable and start txkillswitch service
  systemd:
    name: txkillswitch
    enabled: yes
    state: started
  tags: txkillswitch
