---
- name: remove packages
  yum:
    list: php72w-xml php72w-mysql php72w-fpm mod_php72w php72w-common php72w-intl php72w-gd php72w-pdo php72w-mbstring php72w-cli webtatic-release-7-3
    state: absent
  notify:
    - restart apache

- name: install packages
  yum:
    list: mod_http2 mod_fcgid yum-utils
    state: installed
  notify:
    - restart apache

- name: install Docker
  shell: amazon-linux-extras install docker -y
  args:
    creates: /usr/bin/dockerd

- name: start docker
  service:
    enabled: yes
    name: docker
    state: started

- name: "update httpd.conf"
  template:
    src: httpd.j2.conf
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart apache

- name: "update httpd-le-ssl.conf"
  template:
    src: httpd-le-ssl.j2.conf
    dest: /etc/httpd/conf/httpd-le-ssl.conf
  notify:
    - restart apache

- name: "update conf.d"
  template:
    src: "httpd_conf.d/{{ item }}"
    dest: "/etc/httpd/conf.d/{{ item|regex_replace('\\.j2\\.conf$', '.conf') }}"
  with_items:
    - "getfursu.it.j2.conf"
    - "autoindex.j2.conf"
  notify:
    - restart apache
  tags: conf.d

- name: "update conf.modules.d"
  template:
    src: "httpd_conf.modules.d/{{ item }}"
    dest: "/etc/httpd/conf.modules.d/{{ item|regex_replace('\\.j2\\.conf$', '.conf') }}"
  with_items:
    - "00-mpm.j2.conf"
    - "00-brotli.j2.conf"
    - "00-dav.j2.conf"
    - "00-base.j2.conf"
    - "00-lua.j2.conf"
  notify:
    - restart apache

- name: "update logrotate.d/httpd"
  template:
    src: logrotate.d/httpd.j2
    dest: /etc/logrotate.d/httpd
    backup: yes
