twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        iu_form_url:             '%iu_form_url%'
        request_form_url:        '%request_form_url%'
        feedback_form_url:       '%feedback_form_url%'
        filter_suggest_form_url: '%filter_suggest_form_url%'
