twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        # TODO: Update below simultaneously with #marker-20190407-01
        data_form_url:     https://goo.gl/forms/95dAAq6Sa9ySUcXJ3
        feedback_form_url: https://goo.gl/forms/2mc03Ymr5YdPX7k02
