twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        data_form_url:     https://goo.gl/forms/bmiJFs5QFenKML352
        feedback_form_url: https://goo.gl/forms/2mc03Ymr5YdPX7k02
