twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        iu_form_url:       '%iu_form_url%'
        request_form_url:  '%request_form_url%'
        feedback_form_url: '%feedback_form_url%'
        pma_edit_url:      'http://pma/tbl_change.php?db=fuzzrake&table=artisans&clause_is_unique=1&where_clause=artisans.id%3D'
