###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  database:
    image: mariadb:10.4
    environment:
#      - MYSQL_PASSWORD= # FIXME: ENV or whatever
      - MYSQL_DATABASE=fuzzrake
      - MYSQL_USER=fuzzrake
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    volumes:
      - .:/application
      - ./phpdocker.io/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: phpdocker.io/php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker.io/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
