parameters:
  countries:
    replacements:
      "argentina":                                     "AR"
      "australia":                                     "AU"
      "belgium":                                       "BE"
      "canada":                                        "CA"
      "costa rica":                                    "CR"
      "czech republic":                                "CZ"
      "d[ea]nmark":                                    "DK"
      "germany":                                       "DE"
      "finland":                                       "FI"
      "france":                                        "FR"
      "uk|england|united kingdom":                     "GB"
      "hungary":                                       "HU"
      "ireland":                                       "IE"
      "italia|italy":                                  "IT"
      "mexico":                                        "MX"
      "(the )?netherlands":                            "NL"
      "new zealand":                                   "NZ"
      "russia":                                        "RU"
      "poland":                                        "PL"
      "sweden":                                        "SE"
      "ukraine":                                       "UA"
      "united states( of america)?":                   "US"
      "u\\.?s\\.?( of america)?|usa":                  "US"
      "south africa":                                  "ZA"
