parameters:
  strings:
    replacements:
        "#’#":                 "'"
        "#^-$#":               ""
        "#^Rather not say$#i": ""
        "#^n/a$#i":            ""
        "#^n/a yet$#i":        ""
        "#^-$#i":              ""
        "#[ \t]{2,}#":         " "
      
  lists:
    replacements:
        'Excellent vision &amp; breathability':        'Excellent vision & breathability'
        'backpacks':                                   'Backpacks'
        'claws':                                       'Claws'
        'Armsleeves|Arm Sleeves':                      'Arm sleeves'
        'Head Bases':                                  'Head bases'
        'Plushes':                                     'Plushies'
        'Legsleeves':                                  'Leg sleeves'
        'Fursuit Props':                               'Fursuit props'
        'Sock paws':                                   'Sockpaws'
        'Plush Suits':                                 'Plush suits'
        'Femme Suits':                                 'Femme suits'
        'Just Ask':                                    'Just ask'
        'Removable Eyes':                              'Removable eyes'
        'Pickable Nose':                               'Pickable nose'
        '(.+)changable(.+)':                           '$1changeable$2'
        'Fursuit Sprays?':                             'Fursuit sprays'
        'Dry brushing':                                'Drybrushing'
        'Poseable tongues':                            'Poseable tongue'
        'Bandannas':                                   'Bandanas'
        'Removable Eyelids':                           'Removable eyelids'
