parameters:
  species_definitions:
    valid_choices:
      "Most species": # grep-assumed-does-specie-when-artisan-has-only-doesnt
        "Real life animals":
          Birds:
            Ducks:

          Fishes:
            Sharks:

          Mammals:
            Bears:
              Giant pandas:
            Canines:
              Lupines:
                Wolves:
              Vulpines:
                Foxes:
                  Fennecs:
              Dogs:
            Felines:
              "Big cats":
                Caracals:
                Lions:
                Lynxes:
                Snow leopards:
                Tigers:
              "Small cats":
                "Domestic cats":
            Mustelids:
              Ferrets:
              Otters:
            Primates:
              Apes:
              Monkeys:
            Rodents:
              Mice:
              Rats:
            Ungulates:
              Antelopes:
                Sable antelope:
              Bovines:
                Cows:
              Cervines:
                Deers:
              Equines: # Avoid?
                Horses:
              Goats:
              Rhinos:
              Sheeps:
            Bats:
            Elephants:
            Hyenas:
            Kangaroos:
            Opossums:
            Pinnipeds:
            Rabbits:
            Raccoons:
            Red pandas:

          Reptiles:
            Lizards:

          Bugs:
            Insects:
            Spiders:

          Amphibians:

        "Fantasy creatures":
          Robotic/cybernetic/mechanical:
            Primagens:
              "i_Primagens (on a foam base)":
            Protogens:
              "i_Protogens (on a foam base)":

          "Angel Dragons":
          Crux:
          Digimons:
          Dragons:
          Drekkubuses:
          Dutchies:
          "Dutch Angel Dragons":
          "Ghost Bones Dragon":
          Gryphons:
          Lloteer: # WAT
          Manokits:
          MLP:
          Monsters:
          Pancans:
          Pokemons:
          Sergals:
          "Skull animals":
          Sparkledogs:
          "TV heads":
          Wickerbeasts:

        "All hybrids":
          Hybrids:
            Pancans:
          "i_Hybrids of these":

        Aquatic: # Fill
          Fishes:
          Otters:

        Hooved: # Fill
          MLP:
          Ungulates:

        Scalies: # Fill
          Dinosaurs:
          Dragons:
          Reptiles:

        Winged: # Fill
          Birds:
          "Angel Dragons":
          Bats:
          Dragons:
          "Dutch Angel Dragons":
          Gryphons:
          Pancans:

        With antlers: # Fill
          Antelopes:
          Cervines:
          Goats:

        With beak:
          Birds:
          Pancans: # Add above

        "i_Copyright-related classification?": # FIXME
          "Copyrighted characters":
          "Copyrighted species": # Alias of below?
          "Closed species":
          "Open species":
          "Self-made species":
          "Original species":

      "i_To be fixed": # Just to silence the validator, to be fixed/approved later
        "*Extremely intricate dragons":
        "All species and all fur based characters":
        "Ampwaves": # See protogens/robotic
        "Any animal and most mysticals (dragons*, serials, gryphons)":
        "Any mythical or unique species":
        "Any species that is furry! (canines, felines, fur dragons, horses, rodents, bats, etc.)":
        "Anything requiring extensive electronics (ex: true-to-species protogens, though we could do a simplified \"toony\" version)":
        "Ask for mechanic/electronic creatures":
        "Basic canines, vulpines, angel dragons. (Will consider if unique)":
        "Bugs": # Ambiguous
        "Cervidae/deer family species with large antlers":
        "Characters with overly complicated anatomy (3 mouths, 4 eyes, etc.)":
        "Complex hybrids":
        "Complex species, as if the species has too many parts and details, I will say so during the quote.":
        "Critters":
        "Deer&similar":
        "Dutch Angel Dragons (Tail, paws and feet paws ONLY)":
        "Etc.": # De hecc
        "Extremely intricate anything":
        "Fantasy / mythical creatures":
        "Full robospecies":
        "Gem raptors":
        "Heavily complicated creatures":
        "Humanoids":
        "I can also do velvet or minky skinned characters":
        "I make exceptions on rare occasions":
        "Most anything covered in fur":
        "Most furless/featherless species":
        "Most reptiles":
        "No airbrushed / gradient markings on any species (all work is sewn)":
        "Only because I do not currently have the ability to do the electronic work on them":
        "Others":
        "Please inquire about fantasy creatures":
        "Pony": # Does it mean lil horse or MLP?
        "Protogens (for paws and tail ONLY)":
        "Raptor masks":
        "Rare species":
        "Reptiles (not including dragons)":
        "Robotic stuff":
        "Robots":
        "Sea creatures": # Aquatic?
        "Skull": # Excuse me?
        "Skullsuits":
        "Skull Creatures":
        "Some birds (unless its on another headbase then I'll do it)":
        "Some scalies":
        "Specialises in mythical creatures/monsters":
        "Species with robotic/cybernetic, or otherwise mechanical appearance":
        "Things of an adult nature":
        "Unsafe creations":
        "Ungulates (tests now)":
        "Will not do a closed species without permission": # TODO: Should be equal to closed species; getfursu.it will not help steal designs
        "Will not work with sequin for characters":
        "Your own specific species":

    leave_unchanged:
      - 'Any animal and most mysticals (dragons*, serials, gryphons)'
      - 'Any species that is furry! (canines, felines, fur dragons, horses, rodents, bats, etc.)'
      - 'Anything requiring extensive electronics (ex: true-to-species protogens, though we could do a simplified "toony" version)'
      - 'Basic canines, vulpines, angel dragons. (Will consider if unique)'
      - 'Characters with overly complicated anatomy (3 mouths, 4 eyes, etc.)'
      - 'Dutch Angel Dragons (Tail, paws and feet paws ONLY)'
      - 'Etc.'
      - 'skullsuits...' # FIXME: How the heck am i supposed to interpret that
      - 'Some birds (unless its on another headbase then I''ll do it)'
      - 'Species with robotic/cybernetic, or otherwise mechanical appearance'
      - 'Complex species, as if the species has too many parts and details, I will say so during the quote.'

    replacements:
      '"([^"]+)"':                                                  '$1'

      '(((Any and )?All ?|Anything|Any|all) ?(species?|creatures?|kind|really)( (are )?welcome)?)':    'Most species'
      '(Will(ing)? (to )?(try|craft|do) Any(thing| species)?)':                                        'Most species'
      '((I will do just about|We are okay with|Happy to do) any species!?)':                           'Most species'
      '(I''m (willing|open) to (take on any species|consider anything))':                              'Most species'
      '(Everything and anything|Anything!?|any ?!?|all ?!?)':                                          'Most species'

      '(Almost everything\. Just ask|Almost (all|Any)(thing| species?| animals?)?)':                   'Most species'
      '(All species for the most part|Open to most species|Most animals OK|Most species considered)':  'Most species'
      '(Basically anything! Except what''s stated below|Almost any :\)|Most/Any)':                     'Most species'
      '(Pretty much anything|Just ask|Most common species)':                                           'Most species'
      '^(Any species|Most species)$':                                                                  'Most species'

      '^(None|Nope|no)$':                                    ''
      '(\s|^)(and|or)':                                      '' # FIXME

      'I can craft any real life animal':                    'Real life animals'

      "AD's|(Ange?le? dragons?)":                            'Angel Dragons'
      'Amphibians?':                                         'Amphibians'
      'Antelopes?':                                          'Antelopes'
      'Avians?':                                             'Birds'
      'Bats?':                                               'Bats'
      'Bears?':                                              'Bears'
      'Big/small felines':                                   "Big felines\nSmall felines"
      'Big and small cats':                                  "Big cats\nSmall cats"
      'Big (cats|felines)( in general)?':                    "Big cats"
      'Birds?':                                              'Birds'
      'Birds/avians in general':                             'Birds'
      'Bunn(y|ies)':                                         'Rabbits'
      'Caracles|Caracals?':                                  'Caracals'
      'Cats?( in general)?':                                 'Felines'
      'Canines?( in)? ?(\(?general\)?)?':                    'Canines'
      'Cervines?':                                           'Cervines'
      'copyrighted characters?[ !]*':                        'Copyrighted characters'
      '(any )?Closed? species?':                             'Closed species'
      'Deers?':                                              'Deers'
      'Dinosaurs?':                                          'Dinosaurs'
      'Dogs?':                                               'Dogs'
      'Domestic Cats?':                                      'Domestic cats'
      'Dragons?':                                            'Dragons'
      'Dre[ck]{2}ubus(es)?':                                 'Drekkubuses'
      'Dutch Angel Dragons/Angel Dragons':                   "Dutch Angel Dragons\nAngel Dragons"
      'DAD''s|Dutch ange?le? dragons?':                      'Dutch Angel Dragons'
      'Equines?( in general)?':                              'Equines'
      'Etc\.?':                                              'Etc.'
      'Fantasie':                                            'Fantasy creatures'
      'Felines?( in general)?':                              'Felines'
      'Fennecs?( foxes)?':                                   'Fennecs'
      'Ferrets?':                                            'Ferrets'
      'Fish(es)?':                                           'Fishes'
      'Fox(es)?':                                            'Foxes'
      'Gem Raptors?':                                        'Gem raptors'
      'Goats?':                                              'Goats'
      'Griff[io]ns?':                                        'Gryphons'
      'Horses?':                                             'Horses'
      'Hybride?s?':                                          'Hybrids'
      'Hyenas?':                                             'Hyenas'
      'Humanoids?':                                          'Humanoids'
      'K-?9''?s':                                            'Canines'
      'Kangaroos?':                                          'Kangaroos'
      'Lions?':                                              'Lions'
      'Mammals?( in general)?':                              'Mammals'
      'Mann?okits?':                                         'Manokits'
      'Monkeys?( in general)?':                              'Monkeys'
      'Mouse':                                               'Mice'
      'Open species?':                                       'Open species'
      'Opossums?':                                           'Opossums'
      'Otters?':                                             'Otters'
      'Pandas?':                                             'Giant pandas'
      'Pinnipeds?( in general)?':                            'Pinnipeds'
      'Primagens and protogens':                             "Primagens\nProtogens"
      'Pokemons?':                                           'Pokemons'
      'Primagens?':                                          'Primagens'
      'Protogens?':                                          'Protogens'
      'Protogens/primagens \(on a foam base\)':              "Protogens (on a foam base)\nPrimagens (on a foam base)"
      'Rabbits?':                                            'Rabbits'
      'Racc?oo?ns?':                                         'Raccoons'
      'Rams?':                                               'Sheeps'
      'Rats?':                                               'Rats'
      'Rare/closed species':                                 "Rare species\nClosed species"
      'Red pandas?':                                         'Red pandas'
      'Reptiles?':                                           'Reptiles'
      'Reptilians?( in general)?':                           'Reptiles'
      'Robots?':                                             'Robots'
      'Rodents?( in general)?':                              'Rodents'
      'Sables':                                              'Sable antelope'
      '(any )?Scalies?( in general)?':                       'Scalies'
      'Ser[gi]als?':                                         'Sergals'
      'Sheeps?':                                             'Sheeps'
      'Skull Animals?':                                      'Skull animals'
      'Small felines?':                                      'Small cats'
      'Snow leopards?':                                      'Snow leopards'
      'Wicker ?beas?ts?':                                    'Wickerbeasts'
      'Wolf':                                                'Wolves'
      'Ungulates?(( in)? \(?general\)?)?':                   'Ungulates'
      'Vulpines?':                                           'Vulpines'
