---
- name: reload sshd
  service:
    name: sshd
    state: reloaded

- name: restart Apache
  shell: apachectl configtest && apachectl graceful

- name: reload systemd
  command: systemctl daemon-reload

- name: restart txkillswitch
  service:
    name: txkillswitch
    state: restarted

- name: reboot system
  reboot:
