---
- name: reload sshd
  service:
    name: sshd
    state: reloaded

- name: restart Apache # grep-restart-apache-handler TODO: deduplicate?
  shell: apachectl configtest && apachectl graceful

- name: reload systemd
  command: systemctl daemon-reload

- name: reboot system
  reboot:
