---
- name: install packages
  yum:
    name:
      - brotli
      - brotli-devel
      - httpd
      - httpd-devel
    state: installed

- name: enable Apache
  service:
    enabled: yes
    name: httpd
    state: started

- name: setup firewalld for Apache
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: enabled
  loop:
    - http
    - https

- name: create empty WWW dir
  file:
    group: root
    mode: 0755
    owner: root
    path: "/var/www/empty"
    state: directory

- name: create empty WWW index.html
  copy:
    content: ""
    dest: "/var/www/empty/index.html"
    group: root
    mode: 0644
    owner: root

- name: create /opt/mod_brotli directory
  file:
    group: root
    mode:  0755
    owner: root
    path:  "/opt/mod_brotli"
    state: directory

- name: get mod_brotli.c
  get_url:
    dest: "/opt/mod_brotli/mod_brotli.c"
    url:  "https://raw.githubusercontent.com/apache/httpd/2.4.x/modules/filters/mod_brotli.c"

- name: compile & install mod_brotli
  command: apxs -i -c -l brotlienc mod_brotli.c
  args:
    chdir: "/opt/mod_brotli"

- name: update Apache configuration
  template:
    src: "etc/httpd/{{ item }}"
    dest: "/etc/httpd/{{ item|regex_replace('\\.j2\\.conf$', '.conf') }}"
  with_items:
    - "conf/httpd.j2.conf"
    - "conf.d/autoindex.j2.conf"
    - "conf.d/getfursu.it.j2.conf"
    - "conf.d/welcome.j2.conf"
    - "conf.modules.d/00-base.j2.conf"
    - "conf.modules.d/00-brotli.j2.conf"
    - "conf.modules.d/00-dav.j2.conf"
    - "conf.modules.d/00-lua.j2.conf"
    - "conf.modules.d/00-mpm.j2.conf"
  notify:
    - restart Apache
