---
- name: checkout txkillswitch repo
  git:
    dest:   "/opt/txkillswitch"
    repo:   "https://github.com/veelkoov/txkillswitch.git"
    update: yes

- name: build txkillswitch
  command: cargo build --release
  args:
    chdir: /opt/txkillswitch

- name: create systemd unit for txkillswitch
  template:
    mode: 0644
    src:  "txkillswitch.service.j2"
    dest: "/etc/systemd/system/txkillswitch.service"
  notify:
    - reload systemd
    - restart txkillswitch

- name: enable and start txkillswitch service
  systemd:
    name:    "txkillswitch"
    enabled: yes
    state:   started
