---
- name: setup IPv6-related stuff in sysctl
  template:
    dest: "/etc/sysctl.d/05-ipv6.conf"
    src:  "etc/sysctl.d/05-ipv6.conf"
  notify:
    - reboot system

- name: setup IPv6
  lineinfile:
    line:  "{{ item.name }}={{ item.value }}"
    path:  "/etc/sysconfig/network-scripts/ifcfg-eth0"
    regex: "^{{ item.name }}"
  notify:
    - reboot system
  loop:
    - name:  "IPV6INIT"
      value: "yes"
    - name:  "IPV6_AUTOCONF"
      value: "no"
    - name:  "IPV6_DEFROUTE"
      value: "yes"
    - name:  "IPV6_FAILURE_FATAL"
      value: "no"
    - name:  "IPV6ADDR"
      value: "{{ ipv6_addr }}"
    - name:  "IPV6_DEFAULTGW"
      value: "{{ ipv6_defaultgw }}"
