---
- name: checkout txkillswitch repo
  git:
    dest:   "/opt/txkillswitch"
    repo:   "https://github.com/veelkoov/txkillswitch.git"
    update: yes
  notify:
    - restart txkillswitch # FIXME: Should be triggered by build, but no change detection there yet

- name: build txkillswitch
  command: cargo build --release
  args:
    chdir: /opt/txkillswitch
  # TODO: changed_when + notify

- name: create systemd unit for txkillswitch
  template:
    mode: 0644
    src:  "txkillswitch.service.j2"
    dest: "/etc/systemd/system/txkillswitch.service"
  register: txksstate
  notify:
    - reload systemd
    - restart txkillswitch

- name: suppress txkillswitch during initial setup
  set_fact: # grep-suppress-txkillswitch-yes
    suppress_txkillswitch: "{{ txksstate.diff.before|default('') == '' }}"

- name: enable txkillswitch service
  systemd:
    name:    "txkillswitch"
    enabled: yes
  when: not suppress_txkillswitch
  notify:
    - restart txkillswitch

- name: warn about txkillswitch being suppressed
  debug:
    msg: "WARNING: txkillswitch has not been enabled due to initial setup!"
  when: suppress_txkillswitch
