- hosts: localhost

  vars:
    db_dump_file_path: ../db_dump/artisans.sql

  tasks:
    - set_fact: db_params={{ lookup('ini', 'DATABASE_URL type=properties file=../.env')|urlsplit }}

    - expect:
        command: mysqldump
          --add-drop-table
          --create-options
          --default-character-set=utf8mb4
          --skip-disable-keys
          --skip-extended-insert
          --skip-dump-date
          --skip-comments
          --skip-lock-tables
          --skip-add-locks
          --order-by-primary
          --quote-names
          --tz-utc

          --host={{ db_params.hostname }}
          --port={{ db_params.port }}
          --user={{ db_params.username }}
          --password

          --result-file={{ db_dump_file_path }}

          {{ db_params.path|replace('/', '') }}
        responses:
          password: "{{ db_params.password }}"

    - replace:
        regexp: ",[^,]+,[^,]+\\);$"
        replace: ", NULL, NULL);"
        path: "{{ db_dump_file_path }}"

    - command: git commit -m "Updated DB dump" ../db_dump/artisans.sql
