#!ansible/run.sh
---
- hosts: prod, dev
  tasks:
    - import_role:
        name: db
        tasks_from: read_params

    - set_fact:
        local_db_dump_file_path: "{{ hostvars[groups['dev'][0]]['db_dump_file_path'] }}"

    - import_role:
        name: db
        tasks_from: dump
      when: "'prod' in group_names"

    - import_role:
        name: db
        tasks_from: fetch_dump
      when: "'prod' in group_names"

    - import_role:
        name: db
        tasks_from: replace
      when: "'dev' in group_names"
