- hosts: localhost

  vars:
    sg_name: getfursu.it-backend
    vpc_id: vpc-6d051916

  tasks:
  - shell: curl -4 http://ifconfig.co/ip
    register: ip_output
    args:
      warn: false

  - ec2_group:
      name: "{{ sg_name }}"
      description: getfursu.it backend
      vpc_id: "{{ vpc_id }}"
      rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ ip_output.stdout_lines[0] }}/32"
