#!ansible/run.sh
---
- hosts: local, prod
  tasks:
    - set_fact:
        local_db_path: "{{ hostvars[groups['local'][0]]['db_path'] }}"

    - import_role:
        name: db
        tasks_from: pull
      when: "'prod' in group_names"
