- hosts: aws

  vars:
    pages: [ index, info ]
    upload_list:
      - /index.html
#      - /info.html
#      - /robots.txt
#      - /sitemap.txt
#      - /general.js
#      - /general.css
#      - /Choices-master/assets/styles/css/choices.min.css
#      - /Choices-master/assets/scripts/dist/choices.min.js
#      - /Choices-master/assets/icons/cross.svg
#      - /images/website-banner-bottom.png
#      - /images/website-banner-top.png
#      - /flag-icon-css-master/flags/4x3/at.svg
#      - /flag-icon-css-master/flags/4x3/mx.svg
#      - /flag-icon-css-master/flags/4x3/sk.svg
#      - /flag-icon-css-master/flags/4x3/ar.svg
#      - /flag-icon-css-master/flags/4x3/be.svg
#      - /flag-icon-css-master/flags/4x3/ie.svg

  tasks:
    - file:
        state: absent
        path: ../public/{{ item }}.html
      with_items: "{{ pages }}"

    - shell: curl -s http://fuzzrake/{{ item }}.html | grep -v 'class="sf-toolbar' > ../public/tmpfile && mv ../public/{tmpfile,{{ item }}.html}
      args:
        warn: no
      with_items: "{{ pages }}"

    - aws_s3:
        bucket: fursuit
        mode: put
        permission: private
        src: "../public/{{ item }}"
        object: "{{ item }}"
      with_items: "{{ upload_list }}"

    - file:
        state: absent
        path: ../public/{{ item }}.html
      with_items: "{{ pages }}"

    - cloudfront_invalidation:
        distribution_id: E33VE7XDZBLOTM
        target_paths: "{{ upload_list }}"
