- hosts: localhost

  vars:
    sed_mysql_args_regexp: s/DATABASE_URL=mysql:\/\/([^:]+):([^@]+)@([^:]+):([^\/]+)\/(.+)/-u \1 -p\2 -h \3 -P \4 \5/
    remote_path: /var/www

    cf_distribution_id: E33VE7XDZBLOTM
    ec2_ip: 34.230.64.3
    sg_name: getfursu.it-backend
    vpc_id: vpc-6d051916

    invalidate_list:
      - /index.html
      - /info.html
      - /statistics.html
      - /tracking.html
#      - /robots.txt
#      - /sitemap.txt
#      - /general.js
#      - /main.js
#      - /general.css
#      - /Choices/assets/styles/css/choices.min.css
#      - /Choices/assets/scripts/dist/choices.min.js
#      - /Choices/assets/icons/cross.svg
#      - /images/website-banner-bottom.png
#      - /images/website-banner-top.png
#      - /flag-icon-css/css/flag-icon.min.css
#      - /flag-icon-css/flags/4x3/ar.svg
#      - /flag-icon-css/flags/4x3/at.svg
#      - /flag-icon-css/flags/4x3/au.svg
#      - /flag-icon-css/flags/4x3/be.svg
#      - /flag-icon-css/flags/4x3/br.svg
#      - /flag-icon-css/flags/4x3/ca.svg
#      - /flag-icon-css/flags/4x3/cn.svg
#      - /flag-icon-css/flags/4x3/cz.svg
#      - /flag-icon-css/flags/4x3/de.svg
#      - /flag-icon-css/flags/4x3/dk.svg
#      - /flag-icon-css/flags/4x3/eu.svg
#      - /flag-icon-css/flags/4x3/fi.svg
#      - /flag-icon-css/flags/4x3/fr.svg
#      - /flag-icon-css/flags/4x3/gb.svg
#      - /flag-icon-css/flags/4x3/ie.svg
#      - /flag-icon-css/flags/4x3/it.svg
#      - /flag-icon-css/flags/4x3/mx.svg
#      - /flag-icon-css/flags/4x3/nl.svg
#      - /flag-icon-css/flags/4x3/no.svg
#      - /flag-icon-css/flags/4x3/nz.svg
#      - /flag-icon-css/flags/4x3/pl.svg
#      - /flag-icon-css/flags/4x3/ru.svg
#      - /flag-icon-css/flags/4x3/sk.svg
#      - /flag-icon-css/flags/4x3/tw.svg
#      - /flag-icon-css/flags/4x3/ua.svg
#      - /flag-icon-css/flags/4x3/us.svg

  tasks:
    - block:
      - tempfile:
        register: sql_file

      - set_fact: db_params={{ lookup('ini', 'DATABASE_URL type=properties file=../.env')|urlsplit }}

      - expect:
          command: mysqldump
                     --add-drop-table
                     --create-options
                     --default-character-set=utf8mb4
                     --skip-disable-keys
                     --skip-extended-insert
                     --skip-dump-date
                     --skip-comments
                     --skip-lock-tables
                     --skip-add-locks
                     --order-by-primary
                     --quote-names
                     --tz-utc

                     --host={{ db_params.hostname }}
                     --port={{ db_params.port }}
                     --user={{ db_params.username }}
                     --password

                     --result-file={{ sql_file.path }}

            {{ db_params.path|replace('/', '') }}
          responses:
            password: "{{ db_params.password }}"

      - shell: curl -4 http://ifconfig.co/ip
        register: ip_output
        args:
          warn: false

      - ec2_group:
          name: "{{ sg_name }}"
          description: getfursu.it backend
          vpc_id: "{{ vpc_id }}"
          rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ipv6: ::/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ ip_output.stdout_lines[0] }}/32"

      - shell: ssh {{ ec2_ip }} -C 'mysql $(grep DATABASE_URL= {{ remote_path }}/.env | sed -r "{{ sed_mysql_args_regexp }}")' < {{ sql_file.path }}

      - cloudfront_invalidation:
          distribution_id: "{{ cf_distribution_id }}"
          target_paths: "{{ invalidate_list }}"

      always:
      - file:
          state: absent
          path: "{{ sql_file.path }}"
