---
- replace:
    regexp: "{{ item.regexp }}"
    replace:  "{{ item.replace }}"
    path: "{{ db_dump_file_path }}"
  check_mode: no
  with_items:
    - { regexp: "^INSERT INTO `artisans_commissions_statues` VALUES .+\n", replace: "" }
    - { regexp: "(?<!\\\\)','", replace: "', '" }
    - { regexp: "NULL,'", replace: "NULL, '" }
    - { regexp: ", ?NULL, ?", replace: ", NULL, " }
  no_log: yes

- copy:
    src: "{{ db_dump_file_path }}"
    dest: "{{ committed_db_dump_path }}"
    remote_src: no # FIXME: Wouldn't show diff if yes; works because remote host = localhost

- command: "git commit -m 'Updated DB dump' {{ committed_db_dump_path }}"
