---
- name: dump DB into SQL file
  shell: sqlite3 {{ db_path }} '.dump {{ dumpable_tables|join("' '.dump ") }}' > {{ committed_db_dump_path }} # Is there a nice "map/reduce" in Ansible yet?
  check_mode: no # We assume the result file is non-committed temporary
  changed_when: false

#- replace: # FIXME: restore&improve
#    regexp: "{{ item.regexp }}"
#    replace:  "{{ item.replace }}"
#    path: "{{ committed_db_dump_path }}"
#  check_mode: no
#  with_items:
#    - { regexp: "^INSERT INTO artisans_commissions_statues VALUES.+\n", replace: "" }
#    - { regexp: ",''([,)])", replace: ", ''\\1" }
#    - { regexp: "NULL,'", replace: "NULL, '" }
#    - { regexp: ", ?(NULL|0|1), ?", replace: ", \\1, " }
#    - { regexp: "\\((\\d+),'", replace: "(\\1, '" }
#  no_log: yes
