---
- import_tasks: update_files.yaml
  tags: files

- import_tasks: setup_docker_container.yaml
  tags: docker

- import_tasks: setup_apache_vhost.yaml
  tags: vhost

- import_tasks: clear_cache.yaml
  tags: cache

- import_tasks: build.yaml
  tags: build
