---
- name: create update script
  template:
    dest: "{{ update_script_path }}"
    mode: 0744
    src:  "update.sh.j2"

- name: setup update cronjob
  cron:
    hour:   "6,18"
    name:   "tracker - commissions"
    minute: 0
    value:  "{{ update_script_path|quote }} >> {{ update_log_path|quote }} 2>&1"
