---
- name: assure directory exists
  file:
    group: root
    mode:  0755
    owner: root
    path:  "{{ deployment_path }}"
    state: directory

- name: checkout sources
  git:
    dest: "{{ deployment_path }}"
    force: yes
    repo: https://github.com/veelkoov/fuzzrake.git
    version: "{{ branch }}"

- name: assure var directory is writable
  file:
    group: root
    mode:  0777
    owner: root
    path:  "{{ deployment_path }}/var"
    state: directory

- name: update .env.local
  template:
    dest: "{{ deployment_path }}/.env.local"
    group: root
    mode: 0644
    owner: root
    src: ".env.local.j2"
